### PR TITLE
Add Django 1.10 support

### PR DESCRIPTION
**Pull request by rpkilby**
Simply submitting @edmorley's work from #19. It seems like there was some issues with the way the middleware was implemented, but that this may have been fixed between alpha and beta. Per the comments in #19 `test_middleware_integration_get_auth_view` was failing, but this seems to work now?

### CODE REVIEW

**Comment by helgi** [comment]
You'll want to update the tested Django 1.10 version, like I did in https://github.com/zestedesavoir/django-cors-middleware/pull/23

Would be good to see this PR merged! :)

**Comment by edmorley** [comment]
So the reason I hadn't opened a PR from my branch yet, is that this doesn't actually add proper Django 1.10 support. The tests only pass, since they still use the old `MIDDLEWARE_CLASSES`, rather than Django 1.10's `MIDDLEWARE`.

If people add this middleware to `MIDDLEWARE` the behaviour won't be quite correct due to the issues that I mentioned were left to fix in #19.

Thank you for bumping this however - I'll try to see if I can get back to this soon (if someone else doesn't before me) :-)

**Comment by rpkilby** [comment]
@helgi - whoops, done.
@edmorley - If I'm not mistaken, Django 1.10+ is using the new setting. See [here](https://github.com/rpkilby/django-cors-middleware/blob/fa453b2913216bca4771edd892985b9b069726c9/tests.py#L12-L15). Am I still missing something?

**Comment by helgi** [comment]
Been using this branch with a Django 1.10 project, haven't seen any problems so far

**Comment by vhf** [comment]
LGTM, @gustavi ?

**Comment by gustavi** [comment]
Thank you @rpkilby for this PR :)

**Pull request merged**
