### PR TITLE
Fix #16 : allows dumpdata management command

### LINKED ISSUE #16: corsheaders makes dumpdata management command unavailable
$ python manage.py dumpdata
    CommandError: Unable to serialize database: relation "corsheaders_corsmodel" does not exist
    LINE 1: ...smodel"."id", "corsheaders_corsmodel"."cors" FROM "corsheade...

Manually running `makemigrations` also doesn’t help, because there is no `migrations` module exists under corsheaders. I know from the sources that it is optional (and undocumented!) to use a model for whitelisting, but bricking management commands is not a Good Way To Go™

Adding `corsheaders/migrations/__init__.py` solves the problem, though.

### PR DESCRIPTION
**Pull request by gustavi**
Fix #16

### CODE REVIEW

**Comment by gustavi** [comment]
Sounds like create a bug

**Comment by mitar** [comment]
That does not seem like an initial migration.

**Comment by artragis** [comment]
@gustavi can you give feedback here? Must I take your work and integrate it?

**Comment by gustavi** [comment]
I'll working on it tonight.

**Pull request closed without merging**
