### PR TITLE
Test against Django versions < 2.2

### PR DESCRIPTION
**Pull request by pieterdd**
Updates tox.ini to target Django 1.11, 2.0 and 2.1.

### CODE REVIEW

**Comment by artragis** [comment]
Can you update Readme.md as you clearly added support.

**Comment by pieterdd** [comment]
I don't see them showing up in the CI yet. Hold on, making some edits.

**Comment by pieterdd** [comment]
Updated README.md. Codecov coverage is down because test coverage is generated with Python 3.6 + Django 2.1 and the two unhit lines are - as far as I can tell - only hit by very old versions of Django. Can I remove the backwards compatibility measure to improve the coverage?

**Comment by pieterdd** [comment]
Removed compatibility with outdated Django versions that are no longer supported. Coverage is up now! Anything else?

**Comment by artragis** [comment]
Sorry for the time to answer. 

THanks a lot for this PR.

**Comment by adamchainz** [comment]
https://github.com/ottoyiu/django-cors-headers is now maintained and tested with new Django versions. I also merged over all the features from this fork, IIRC. I'd prefer if this fork was updated to redirect users back to the original. I checked Django 2.0 and 2.1 support since they came out.

**Pull request merged**
